import { ThemeProvider } from "@/components/ThemeProvider"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<head />
			<body className='min-h-screen'>
				<ThemeProvider attribute='class' defaultTheme='system' enableSystem>
					{children}
				</ThemeProvider>
				<div className='border-t text-sm text-gray-500 py-4 border-gray-300 text-center'>
					© 2023. codewithagus. All rights reserved
				</div>
			</body>
		</html>
	)
}
